name: CI-CD
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da base de códigos
        uses: actions/checkout@v3.6.0
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construindo a imagem do worker
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            tarikdimitri/rotten-potatoes:{{github.run_number}}
            tarikdimitri/rotten-potatoes:latest
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout da base de códigos
        uses: actions/checkout@v3.6.0
      - name: Configurar as credenciais de acesso
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-eaast-1
      - name: Configuração do Kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name imersao-eks-tarik --region us-east-1
      - name: Deploy no Cluster Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./src/deployment.yaml
          images: |
            tarikdimitri/rotten-potatoes:{{github.run_number}}
